### ISSUE TITLE
utils 类中注释中包含错别字

### ISSUE THREAD

**Issue by anjiemo** [tursom/TursomServer#1]
[utils](https://github.com/tursom/TursomServer/blob/78b79bedec486bdcb8ba919bf25b0decbb3dd2e3/ts-core/src/main/kotlin/cn/tursom/core/utils.kt#L115)

 "使用 condition 做条件判断，如果返回 true 则使用 then 生成结果，否则范湖自身" 应修改为 "使用 condition 做条件判断，如果返回 true 则使用 then 生成结果，否则 **返回** 自身"

**Comment by tursom** [comment]
commit 225adfa9 fix
